Add example as a notebook: example_na_controlling_the_pml
waltsims/k-wave-python pull request #217
Opened 2023-10-08 16:15 UTC by faridyagubbayli

TODO

2023-11-09 19:17 UTC, yfarid-lilt commented on examples/example_na_controlling_the_pml/README.md
> +and comparing them against Pyton version. Saving the variable states can be done manually by running the Matlab script,
Fix the typo here, thanks @waltsims for catching this!

2023-11-09 19:47 UTC, waltsims requested changes
Hey Farid!

Amazing PR. The output plot of the notebook looks like it needs to be fixed.

2024-01-10 20:31 UTC, waltsims commented
[This](https://github.com/waltsims/k-wave-python/blob/991c891aa8493e66ec4bc12efb098eb6f018b9d8/examples/at_array_as_sensor/at_array_as_sensor.py#L63) might be the method we need to fix this example. I am leaving this comment for myself later.

2024-01-15 05:15 UTC, waltsims commented
> [This](https://github.com/waltsims/k-wave-python/blob/991c891aa8493e66ec4bc12efb098eb6f018b9d8/examples/at_array_as_sensor/at_array_as_sensor.py#L63) might be the method we need to fix this example. I am leaving this comment for myself later.

This indeed worked.

2024-01-15 05:16 UTC, waltsims commented
@faridyagubbayli please check again that get_color_map works as intended. perhaps we could make a test so we can test it in all python versions? I was having issues with python 3.8.

2024-01-15 05:23 UTC, waltsims approved these changes

2024-01-15 05:23 UTC, waltsims commented on tests/matlab_test_data_collectors/python_testers/getColorMap_test.py
Please make sure the example follows the passing proper usage and we're good!

2024-01-15 05:51 UTC, waltsims commented
> [This](https://github.com/waltsims/k-wave-python/blob/991c891aa8493e66ec4bc12efb098eb6f018b9d8/examples/at_array_as_sensor/at_array_as_sensor.py#L63) might be the method we need to fix this example. I am leaving this comment for myself later.

This should be updated in the logic kWaveSimulation. There is an option there but it seems the logic doesn't work atm. Same in kwave?

2024-01-15 20:53 UTC, faridyagubbayli commented
@waltsims going to merge this soon, please let me know if I should not. I agree that we can fix the method you linked in the next point release.

2024-01-15 20:56 UTC, waltsims commented
Im happy to change the color map in the notebook and add 'update colormap' as an enhancement for the next point release. All examples will need it!

2024-01-15 21:10 UTC, waltsims commented
I made the change. Just test the notebook please.

2024-01-16 10:01 UTC, faridyagubbayli commented
@waltsims thanks for making the change! I tested the notebook. Although colors are different, everything seems fine. Going to merge.

2024-01-16 10:02 UTC, merged