Auto chunking for HDF5
waltsims/k-wave-python pull request #222
Opened 2023-11-03 08:24 UTC by djps

could close #173 - it remains an open question what the default chunking should be though.

2023-11-06 14:31 UTC, peterhollender requested changes
I like the functionality, but I think we can accomplish this all by just changing line 184 to `'chunks': True if auto_chunk else tuple(chunk_size)`, since `chunk_size` isn't used for anything other than populating `opts`. 

My only other concern is that we haven't provided a way to invoke this option, since it isn't activated by default. Should we add the option to `save_h5_file`, `save_file`, and `save_to_disk_func` and `kspaceFirstOrder3D`? This way you could invoke it by calling `output = kspaceFirstOrder3D(..., auto_chunk=True)`

2023-11-07 15:32 UTC, waltsims commented
At first glance, I see no reason to no always use auto chunking.

2023-11-30 21:23 UTC, waltsims requested changes

2023-11-30 23:04 UTC, waltsims commented
@peterhollender @djps and I have made some changes based on your suggestions. Thanks for your input!

2023-11-30 23:24 UTC, merged